version: '3.1'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_USER: admin
      MYSQL_PASSWORD: abc123
      MYSQL_DATABASE: shiny
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    expose:
          - 3306
volumes:
  mysql_data:
    driver: local